name: Main Branch CI

on:
  push:
    branches:
      - main

jobs:
  test-lint:
    name: "Cargo build, test"
    runs-on: codeberg-medium

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: siebert/setup-rust@stable

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --all --verbose

  bump-and-publish:
    runs-on: codeberg-medium
    if: forgejo.ref == 'refs/heads/main'
    name: Cargo bump patch and publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.FORGEJO_TOKEN }}

      - name: Install Rust
        uses: siebert/setup-rust@stable

      - name: Install cargo-edit
        run: cargo install cargo-edit

      - name: Bump patch version
        run: |
          cargo set-version --bump patch
          cargo update

      - name: Commit version bump
        run: |
          git config user.name "CI"
          git config user.email "ci@codeberg.org"
          git commit -am "chore: bump patch version [skip ci]"
          git push

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --locked
